services:
  prestashop.module_example.form.type.demo_configuration_text:
    class: 'PrestaShop\ModuleExample\Form\ModuleExampleTextForm'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module_example.form.demo_configuration_text_form_data_provider:
    class: 'PrestaShop\ModuleExample\Form\ModuleExampleTextFormDataProvider'
    arguments:
      - '@prestashop.module_example.form.demo_configuration_text_data_configuration'

  prestashop.module_example.form.demo_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module_example.form.demo_configuration_text_form_data_provider'
      - 'PrestaShop\ModuleExample\Form\ModuleExampleTextForm'
      - 'ModuleExampleForm'
    public: true

  prestashop.module_example.form.demo_configuration_text_data_configuration:
    class: PrestaShop\ModuleExample\Form\ModuleExampleTextDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']
    
  # Grid services
  demo_grid.grid.definition.factory.products:
    class: 'PrestaShop\ModuleExample\Grid\Definition\Factory\ProductGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  demo_grid.grid.query_builder.product:
    class: 'PrestaShop\ModuleExample\Grid\Query\ProductQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'

  demo_grid.grid.data_provider.products:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@demo_grid.grid.query_builder.product'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'product'

  demo_grid.grid.factory.products:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@demo_grid.grid.definition.factory.products'
      - '@demo_grid.grid.data_provider.products'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

