ps_controller_tabs_moduleexampleconfigure:
  path: /configure-moduleexample
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\ModuleExample\Controller\Admin\ModuleExampleConfigureController::indexAction'
    _legacy_controller: 'AdminModuleExampleControllerTabsConfigure'
    _legacy_link: 'AdminModuleExampleControllerTabsConfigure'

ps_controller_form_moduleexample:
  path: /form-moduleexample
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\ModuleExample\Controller\ModuleExampleFormController::index'
    _legacy_controller: AdminModuleExampleControllerForm
    _legacy_link: AdminModuleExampleControllerForm
